/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
luu ý:
set Form có layout là border layout

 */
package gui;

import common.Shared;
import dao.NguoiDungDAO;
import dto.NguoiDung;
/**
 *
 * @author w7
 */
public class mainForm extends javax.swing.JFrame {

    private StudentManagementJPanel StudentManagementJPanel;
    private GPA_ManagementJPanel GPA_ManagementJPanel;
    
    /**
     * Creates new form mainForm
     */
    public mainForm() {
        initComponents();
        setSize(700,600);
    }
    public void PhanQuyen()
    {
        NguoiDung user=Shared.user;
        lbUser.setText("Tên đăng nhập: "+user.getTenDangNhap()+" ;Vai trò: "+user.getVaiTro());
        if(user.getVaiTro().equalsIgnoreCase("GiangVien"))
        {
           btnQuanLySinhVien.setEnabled(false);
           btnQuanLyDiem.setEnabled(true);
        }else if (user.getVaiTro().equalsIgnoreCase("CanBoDaoTao")) {
            btnQuanLyDiem.setEnabled(false);
            btnQuanLySinhVien.setEnabled(true);
        }
        tabMain.removeAll();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jToolBar1 = new javax.swing.JToolBar();
        btnDangXuat = new javax.swing.JButton();
        btnQuanLySinhVien = new javax.swing.JButton();
        btnQuanLyDiem = new javax.swing.JButton();
        lbUser = new javax.swing.JLabel();
        tabMain = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ứng dụng quản lý điểm");

        jToolBar1.setRollover(true);

        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout-icon-32.png"))); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setFocusable(false);
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnDangXuat);

        btnQuanLySinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/10207-man-student-light-skin-tone-icon-32.png"))); // NOI18N
        btnQuanLySinhVien.setText("Quản lý sinh viên");
        btnQuanLySinhVien.setFocusable(false);
        btnQuanLySinhVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQuanLySinhVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQuanLySinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLySinhVienActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQuanLySinhVien);

        btnQuanLyDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/gpa-icon-32.png"))); // NOI18N
        btnQuanLyDiem.setText("Quản lý điểm");
        btnQuanLyDiem.setFocusable(false);
        btnQuanLyDiem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQuanLyDiem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQuanLyDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyDiemActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQuanLyDiem);

        lbUser.setText("jLabel1");
        jToolBar1.add(lbUser);

        jMenu1.setText("Hệ thống");

        jMenuItem1.setText("Đăng xuất");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");

        jMenuItem3.setText("Quản lý sinh viên");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Quản lý điểm");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Trợ giúp");

        jMenuItem5.setText("Hướng dẫn sử dụng");
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("Giới thiệu");
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabMain, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabMain, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(599, 449));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuanLySinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLySinhVienActionPerformed
        // TODO add your handling code here:
        if(StudentManagementJPanel==null)
        {
            StudentManagementJPanel=new StudentManagementJPanel();
            tabMain.addTab("Quan ly sinh vien", StudentManagementJPanel);
        }
    }//GEN-LAST:event_btnQuanLySinhVienActionPerformed

    private void btnQuanLyDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyDiemActionPerformed
        // TODO add your handling code here:
        if(GPA_ManagementJPanel==null)
        {
            GPA_ManagementJPanel=new GPA_ManagementJPanel();
            tabMain.addTab("Quản lý điểm", GPA_ManagementJPanel);
        }
    }//GEN-LAST:event_btnQuanLyDiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mainForm mainForm1=new mainForm();
                mainForm1.setVisible(true);
               loginDialog login=new loginDialog(mainForm1, true);
               login.setLocationRelativeTo(mainForm1);
               login.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnQuanLyDiem;
    private javax.swing.JButton btnQuanLySinhVien;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbUser;
    private javax.swing.JTabbedPane tabMain;
    // End of variables declaration//GEN-END:variables
}
